AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Infrastructure for StudySync
Parameters:
  ImageId:
    Description: AMI to use eg. ami-0947d2ba12ee1ff75
    Default: ami-0947d2ba12ee1ff75
    Type: String
  VpcId:
    Description: The VPC used by the SG
    Type: String
Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref ImageId
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: "Open port 80"
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: "0.0.0.0/0"
